spring.application.name=cafeProject

server.port=9006

spring.devtools.restart.enabled=true

spring.devtools.livereload.enabled=true

# mariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/cafeProject
spring.datasource.username=cafeProjectUser
spring.datasource.password=1234

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# img folder
## \uC2E4\uC81C \uD30C\uC77C\uC774 \uC800\uC7A5\uB420 \uD3F4\uB354 (\uBB3C\uB9AC \uACBD\uB85C)
app.image.upload-dir=C:/dw202/attach/summernote/
## \uD074\uB77C\uC774\uC5B8\uD2B8\uAC00 img src\uB85C \uC4F8 URL prefix
app.image.url-prefix=/dw202/attach/summernote/

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.hibernate.type.descriptor.sql=trace

logging.level.org.springframework.security.web.csrf=DEBUG

logging.pattern.console=%d{HH:mm:ss} %-5level - %msg%n

# \uD30C\uC77C \uC5C5\uB85C\uB4DC \uD5C8\uC6A9 \uD06C\uAE30
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.thymeleaf.cache=false